// Auto-generated. Do not edit!

// (in-package my_package.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class myActionGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goal_header = null;
      this.maximumCharge = null;
    }
    else {
      if (initObj.hasOwnProperty('goal_header')) {
        this.goal_header = initObj.goal_header
      }
      else {
        this.goal_header = new std_msgs.msg.Header();
      }
      if (initObj.hasOwnProperty('maximumCharge')) {
        this.maximumCharge = initObj.maximumCharge
      }
      else {
        this.maximumCharge = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type myActionGoal
    // Serialize message field [goal_header]
    bufferOffset = std_msgs.msg.Header.serialize(obj.goal_header, buffer, bufferOffset);
    // Serialize message field [maximumCharge]
    bufferOffset = _serializer.int32(obj.maximumCharge, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type myActionGoal
    let len;
    let data = new myActionGoal(null);
    // Deserialize message field [goal_header]
    data.goal_header = std_msgs.msg.Header.deserialize(buffer, bufferOffset);
    // Deserialize message field [maximumCharge]
    data.maximumCharge = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.Header.getMessageSize(object.goal_header);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_package/myActionGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3cba772f93883575bbc47c2ecc654bb3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    std_msgs/Header goal_header
    int32 maximumCharge
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new myActionGoal(null);
    if (msg.goal_header !== undefined) {
      resolved.goal_header = std_msgs.msg.Header.Resolve(msg.goal_header)
    }
    else {
      resolved.goal_header = new std_msgs.msg.Header()
    }

    if (msg.maximumCharge !== undefined) {
      resolved.maximumCharge = msg.maximumCharge;
    }
    else {
      resolved.maximumCharge = 0
    }

    return resolved;
    }
};

module.exports = myActionGoal;
