; Auto-generated. Do not edit!


(cl:in-package my_package-msg)


;//! \htmlinclude my_actionFeedback.msg.html

(cl:defclass <my_actionFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback_header
    :reader feedback_header
    :initarg :feedback_header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (currentCharge
    :reader currentCharge
    :initarg :currentCharge
    :type cl:integer
    :initform 0))
)

(cl:defclass my_actionFeedback (<my_actionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <my_actionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'my_actionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_package-msg:<my_actionFeedback> is deprecated: use my_package-msg:my_actionFeedback instead.")))

(cl:ensure-generic-function 'feedback_header-val :lambda-list '(m))
(cl:defmethod feedback_header-val ((m <my_actionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_package-msg:feedback_header-val is deprecated.  Use my_package-msg:feedback_header instead.")
  (feedback_header m))

(cl:ensure-generic-function 'currentCharge-val :lambda-list '(m))
(cl:defmethod currentCharge-val ((m <my_actionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_package-msg:currentCharge-val is deprecated.  Use my_package-msg:currentCharge instead.")
  (currentCharge m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <my_actionFeedback>) ostream)
  "Serializes a message object of type '<my_actionFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'feedback_header) ostream)
  (cl:let* ((signed (cl:slot-value msg 'currentCharge)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <my_actionFeedback>) istream)
  "Deserializes a message object of type '<my_actionFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'feedback_header) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'currentCharge) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<my_actionFeedback>)))
  "Returns string type for a message object of type '<my_actionFeedback>"
  "my_package/my_actionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'my_actionFeedback)))
  "Returns string type for a message object of type 'my_actionFeedback"
  "my_package/my_actionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<my_actionFeedback>)))
  "Returns md5sum for a message object of type '<my_actionFeedback>"
  "255e3dbd719fbd4e6732b6bf7e9de092")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'my_actionFeedback)))
  "Returns md5sum for a message object of type 'my_actionFeedback"
  "255e3dbd719fbd4e6732b6bf7e9de092")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<my_actionFeedback>)))
  "Returns full string definition for message of type '<my_actionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%std_msgs/Header feedback_header~%int32 currentCharge~%~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'my_actionFeedback)))
  "Returns full string definition for message of type 'my_actionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%std_msgs/Header feedback_header~%int32 currentCharge~%~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <my_actionFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'feedback_header))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <my_actionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'my_actionFeedback
    (cl:cons ':feedback_header (feedback_header msg))
    (cl:cons ':currentCharge (currentCharge msg))
))
