; Auto-generated. Do not edit!


(cl:in-package my_package-msg)


;//! \htmlinclude myActionResult.msg.html

(cl:defclass <myActionResult> (roslisp-msg-protocol:ros-message)
  ((result_header
    :reader result_header
    :initarg :result_header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_reached
    :reader goal_reached
    :initarg :goal_reached
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass myActionResult (<myActionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <myActionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'myActionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_package-msg:<myActionResult> is deprecated: use my_package-msg:myActionResult instead.")))

(cl:ensure-generic-function 'result_header-val :lambda-list '(m))
(cl:defmethod result_header-val ((m <myActionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_package-msg:result_header-val is deprecated.  Use my_package-msg:result_header instead.")
  (result_header m))

(cl:ensure-generic-function 'goal_reached-val :lambda-list '(m))
(cl:defmethod goal_reached-val ((m <myActionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_package-msg:goal_reached-val is deprecated.  Use my_package-msg:goal_reached instead.")
  (goal_reached m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <myActionResult>) ostream)
  "Serializes a message object of type '<myActionResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'result_header) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'goal_reached) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <myActionResult>) istream)
  "Deserializes a message object of type '<myActionResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'result_header) istream)
    (cl:setf (cl:slot-value msg 'goal_reached) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<myActionResult>)))
  "Returns string type for a message object of type '<myActionResult>"
  "my_package/myActionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'myActionResult)))
  "Returns string type for a message object of type 'myActionResult"
  "my_package/myActionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<myActionResult>)))
  "Returns md5sum for a message object of type '<myActionResult>"
  "16b66d62c836ef7c10106a7a2ba9ddcc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'myActionResult)))
  "Returns md5sum for a message object of type 'myActionResult"
  "16b66d62c836ef7c10106a7a2ba9ddcc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<myActionResult>)))
  "Returns full string definition for message of type '<myActionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/Header result_header~%bool goal_reached~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'myActionResult)))
  "Returns full string definition for message of type 'myActionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%std_msgs/Header result_header~%bool goal_reached~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <myActionResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'result_header))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <myActionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'myActionResult
    (cl:cons ':result_header (result_header msg))
    (cl:cons ':goal_reached (goal_reached msg))
))
