// Generated by gencpp from file my_package/myActionFeedback.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_MYACTIONFEEDBACK_H
#define MY_PACKAGE_MESSAGE_MYACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace my_package
{
template <class ContainerAllocator>
struct myActionFeedback_
{
  typedef myActionFeedback_<ContainerAllocator> Type;

  myActionFeedback_()
    : feedback_header()
    , currentCharge(0)  {
    }
  myActionFeedback_(const ContainerAllocator& _alloc)
    : feedback_header(_alloc)
    , currentCharge(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _feedback_header_type;
  _feedback_header_type feedback_header;

   typedef int32_t _currentCharge_type;
  _currentCharge_type currentCharge;





  typedef boost::shared_ptr< ::my_package::myActionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_package::myActionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct myActionFeedback_

typedef ::my_package::myActionFeedback_<std::allocator<void> > myActionFeedback;

typedef boost::shared_ptr< ::my_package::myActionFeedback > myActionFeedbackPtr;
typedef boost::shared_ptr< ::my_package::myActionFeedback const> myActionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_package::myActionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_package::myActionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_package::myActionFeedback_<ContainerAllocator1> & lhs, const ::my_package::myActionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.feedback_header == rhs.feedback_header &&
    lhs.currentCharge == rhs.currentCharge;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_package::myActionFeedback_<ContainerAllocator1> & lhs, const ::my_package::myActionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_package::myActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_package::myActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::myActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::myActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::myActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::myActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_package::myActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "255e3dbd719fbd4e6732b6bf7e9de092";
  }

  static const char* value(const ::my_package::myActionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x255e3dbd719fbd4eULL;
  static const uint64_t static_value2 = 0x6732b6bf7e9de092ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_package::myActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_package/myActionFeedback";
  }

  static const char* value(const ::my_package::myActionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_package::myActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"std_msgs/Header feedback_header\n"
"int32 currentCharge\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::my_package::myActionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_package::myActionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback_header);
      stream.next(m.currentCharge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myActionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_package::myActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_package::myActionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.feedback_header);
    s << indent << "currentCharge: ";
    Printer<int32_t>::stream(s, indent + "  ", v.currentCharge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_MYACTIONFEEDBACK_H
