// Generated by gencpp from file my_package/myActionGoal.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_MYACTIONGOAL_H
#define MY_PACKAGE_MESSAGE_MYACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace my_package
{
template <class ContainerAllocator>
struct myActionGoal_
{
  typedef myActionGoal_<ContainerAllocator> Type;

  myActionGoal_()
    : goal_header()
    , maximumCharge(0)  {
    }
  myActionGoal_(const ContainerAllocator& _alloc)
    : goal_header(_alloc)
    , maximumCharge(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _goal_header_type;
  _goal_header_type goal_header;

   typedef int32_t _maximumCharge_type;
  _maximumCharge_type maximumCharge;





  typedef boost::shared_ptr< ::my_package::myActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_package::myActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct myActionGoal_

typedef ::my_package::myActionGoal_<std::allocator<void> > myActionGoal;

typedef boost::shared_ptr< ::my_package::myActionGoal > myActionGoalPtr;
typedef boost::shared_ptr< ::my_package::myActionGoal const> myActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_package::myActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_package::myActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_package::myActionGoal_<ContainerAllocator1> & lhs, const ::my_package::myActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.goal_header == rhs.goal_header &&
    lhs.maximumCharge == rhs.maximumCharge;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_package::myActionGoal_<ContainerAllocator1> & lhs, const ::my_package::myActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_package::myActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_package::myActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::myActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::myActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::myActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::myActionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_package::myActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cba772f93883575bbc47c2ecc654bb3";
  }

  static const char* value(const ::my_package::myActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cba772f93883575ULL;
  static const uint64_t static_value2 = 0xbbc47c2ecc654bb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_package::myActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_package/myActionGoal";
  }

  static const char* value(const ::my_package::myActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_package::myActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"std_msgs/Header goal_header\n"
"int32 maximumCharge\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::my_package::myActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_package::myActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_header);
      stream.next(m.maximumCharge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_package::myActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_package::myActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_header);
    s << indent << "maximumCharge: ";
    Printer<int32_t>::stream(s, indent + "  ", v.maximumCharge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_MYACTIONGOAL_H
