// Generated by gencpp from file my_package/srv1.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_SRV1_H
#define MY_PACKAGE_MESSAGE_SRV1_H

#include <ros/service_traits.h>


#include <my_package/srv1Request.h>
#include <my_package/srv1Response.h>


namespace my_package
{

struct srv1
{

typedef srv1Request Request;
typedef srv1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv1
} // namespace my_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_package::srv1 > {
  static const char* value()
  {
    return "0a43d4272d4a6822c4aaf349b302052f";
  }

  static const char* value(const ::my_package::srv1&) { return value(); }
};

template<>
struct DataType< ::my_package::srv1 > {
  static const char* value()
  {
    return "my_package/srv1";
  }

  static const char* value(const ::my_package::srv1&) { return value(); }
};


// service_traits::MD5Sum< ::my_package::srv1Request> should match
// service_traits::MD5Sum< ::my_package::srv1 >
template<>
struct MD5Sum< ::my_package::srv1Request>
{
  static const char* value()
  {
    return MD5Sum< ::my_package::srv1 >::value();
  }
  static const char* value(const ::my_package::srv1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package::srv1Request> should match
// service_traits::DataType< ::my_package::srv1 >
template<>
struct DataType< ::my_package::srv1Request>
{
  static const char* value()
  {
    return DataType< ::my_package::srv1 >::value();
  }
  static const char* value(const ::my_package::srv1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_package::srv1Response> should match
// service_traits::MD5Sum< ::my_package::srv1 >
template<>
struct MD5Sum< ::my_package::srv1Response>
{
  static const char* value()
  {
    return MD5Sum< ::my_package::srv1 >::value();
  }
  static const char* value(const ::my_package::srv1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package::srv1Response> should match
// service_traits::DataType< ::my_package::srv1 >
template<>
struct DataType< ::my_package::srv1Response>
{
  static const char* value()
  {
    return DataType< ::my_package::srv1 >::value();
  }
  static const char* value(const ::my_package::srv1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_SRV1_H
