// Generated by gencpp from file my_package/srv2Response.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_SRV2RESPONSE_H
#define MY_PACKAGE_MESSAGE_SRV2RESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_package
{
template <class ContainerAllocator>
struct srv2Response_
{
  typedef srv2Response_<ContainerAllocator> Type;

  srv2Response_()
    {
    }
  srv2Response_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::my_package::srv2Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_package::srv2Response_<ContainerAllocator> const> ConstPtr;

}; // struct srv2Response_

typedef ::my_package::srv2Response_<std::allocator<void> > srv2Response;

typedef boost::shared_ptr< ::my_package::srv2Response > srv2ResponsePtr;
typedef boost::shared_ptr< ::my_package::srv2Response const> srv2ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_package::srv2Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_package::srv2Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace my_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_package::srv2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_package::srv2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::srv2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::srv2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::srv2Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::srv2Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_package::srv2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::my_package::srv2Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_package::srv2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_package/srv2Response";
  }

  static const char* value(const ::my_package::srv2Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_package::srv2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::my_package::srv2Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_package::srv2Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv2Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_package::srv2Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::my_package::srv2Response_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_SRV2RESPONSE_H
