// Generated by gencpp from file my_package/srv2.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_SRV2_H
#define MY_PACKAGE_MESSAGE_SRV2_H

#include <ros/service_traits.h>


#include <my_package/srv2Request.h>
#include <my_package/srv2Response.h>


namespace my_package
{

struct srv2
{

typedef srv2Request Request;
typedef srv2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv2
} // namespace my_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_package::srv2 > {
  static const char* value()
  {
    return "7a81d6a911dd350f0f2b592be405d547";
  }

  static const char* value(const ::my_package::srv2&) { return value(); }
};

template<>
struct DataType< ::my_package::srv2 > {
  static const char* value()
  {
    return "my_package/srv2";
  }

  static const char* value(const ::my_package::srv2&) { return value(); }
};


// service_traits::MD5Sum< ::my_package::srv2Request> should match
// service_traits::MD5Sum< ::my_package::srv2 >
template<>
struct MD5Sum< ::my_package::srv2Request>
{
  static const char* value()
  {
    return MD5Sum< ::my_package::srv2 >::value();
  }
  static const char* value(const ::my_package::srv2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package::srv2Request> should match
// service_traits::DataType< ::my_package::srv2 >
template<>
struct DataType< ::my_package::srv2Request>
{
  static const char* value()
  {
    return DataType< ::my_package::srv2 >::value();
  }
  static const char* value(const ::my_package::srv2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_package::srv2Response> should match
// service_traits::MD5Sum< ::my_package::srv2 >
template<>
struct MD5Sum< ::my_package::srv2Response>
{
  static const char* value()
  {
    return MD5Sum< ::my_package::srv2 >::value();
  }
  static const char* value(const ::my_package::srv2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package::srv2Response> should match
// service_traits::DataType< ::my_package::srv2 >
template<>
struct DataType< ::my_package::srv2Response>
{
  static const char* value()
  {
    return DataType< ::my_package::srv2 >::value();
  }
  static const char* value(const ::my_package::srv2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_SRV2_H
